from models.db import db

class Stats(db.Model)
    id = db.Column(db.Integer, primary_key=True)
    game_id = db.Column(db.Integer)
    player_id = db.Column(db.Integer)
    goals = db.Column(db.Integer)
    assists = db.Column(db.Integer)
    second_assist = db.Column(db.Integer)
    d_blocks = db.Column(db.Integer)
    completions = db.Column(db.Integer)
    throwaways = db.Column(db.Integer)
    threw_drop = db.Column(db.Integer)
    catches = db.Column(db.Integer)
    drops = db.Column(db.Integer)
    pick_ups = db.Column(db.Integer)
    pulls = db.Column(db.Integer)
    calihan = db.Column(db.Integer)
    o_points_for = db.Column(db.Integer)
    o_points_against = db.Column(db.Integer)
    d_points_for = db.Column(db.Integer)
    d_points_against = db.Column(db.Integer)
